{% set name = "openactive" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openactive-{{ version }}.tar.gz
  sha256: 57ec1248a6b21a4663f00f9c5f6a4279d028426b34732d13b84be57db63196fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.7
    - beautifulsoup4
    - requests
    - termcolor

test:
  imports:
    - openactive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openactive/openactive-python
  summary: For reading feeds of sports and activity data published in the OpenActive format
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Reikyo
