{% set name = "openactive" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openactive-{{ version }}.tar.gz
  sha256: a3ef993694d8b89d8ccf6771468fa1f0d05231c7e958a14e873db0d1ad9f74ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.7
    - beautifulsoup4
    - requests
    - termcolor

test:
  imports:
    - openactive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openactive/openactive-python
  summary: For reading feeds of sports and activity data published in the OpenActive format
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Reikyo
